language: java
jdk:
- openjdk8
install:
- mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: heroku
  api_key:
    secure: lXvNljfbSN3jwhsFGOSLVvpIXvVh7S76FupaaCtbVjjUE4kjVRAXedfV17XW43IgqUBvcYAYmx17OxfWW06wR6r4cY91m+sHWHjmC5ahNwHw/xpxvOot0il1vC8RiRCXKxufNzO+AsZ3HudkWcl91R7Lw8B8003JBXkKY4PeQ7ytJ1JxTb2wXhC7L1emnEMWbmrcENT5GG5vRHISsTnvCoS8EM2Tksc9x9v4ekHigVuA258mrqrtMSWKfMGwbb2Js1ku4i3FAAbzHGMQiKb3acYzZEHg08V+EvwvlwOMzmFN9bkzeW3dYp0Ycrp07cminrMLwCM1jlfU73yN1+Z9vCHDTUxBwvBS39hpIcD7YMISfcisFhbkBs+Avj2N5IKZbf9iJs084a7TY9AHry45aFlsa+BbKcgN8scCQ8pLhrp6NWrAvh99ebI7bExLmmfoKigpSin/z4oVcCU/jC0yq+A5DgZY04cgwkmBvQjfnSnyOtQ8dPQtxN9KAnv5W66dYn46cu/deW6ze4Z9WST7uCjaFAoAfK30bPtBa7PYAXg/hc8mwYjBHOa1EF9l4boLad/yl2JDNOTJhQhx2fbiNa4MwHg2X/dXhEwM5C2rf6f6zaXx0Egy8LYfyRUk/YSW7Zn65HDYYa4lwfoiC5duWT/7rYETeeaXTX9SIAHShoE=
    app: retro-feedback
script:
- mvn test jacoco:report
after_success:
- mvn coveralls:report
