language: java
jdk:
- openjdk8
install:
- mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: heroku
  api_key:
    secure: Te49RIwJRJtkEY/6t9noG2j10pv0+HnWA7YzkHU9M+7Y8zIPpAEMpo6L2BjOEZCdq9/zwnmPQXHV4xuCMs2fU2t4pHptIBya3hd8blqeKtsUuMN7cD/lzB3JURo4sd9DD9vgexvYGxLnXzCkXjmLk1ojFxwZ09bZzzrG/3tOxPM8jeQgrNqVYgMOE0gMbCWC2yuDHS8RL6WXohy7qOu/XcjLHMf1KwhMLV9W9iE4GvfHAKLpyqsrfMcUDDGVJ708nREL4U4TN7VVidwiCrMk6p+XnPnmNK+IboNKoHz6j7uJF2Pz5p6CY69RcKkebAObrs+RA5MFwdh4HgZLio+2YbR8Y9hDvhBA3dHjWGHa5n0iPywM/QGaEXK6es7H/kE9bzXADe6XS2og2cyKPMH/DR0X+owC9ulAuqC36DS54pvL68qU5fXUf6M4VdT3tDNYlgRJRW6sKFUyd2ktNv++xOQ4OKmurXo459UsAZXsfmWde7UK2Ce7UJLQsLyISHC3YOUicI8tcvhnrlE8qmu3tOiXbIXZR0hP7dJI+7kTOCNqhps6hMNV11CCh0f3yRpUNb+XmNNNH6kNm+oN31/e7TeMwK9NRQpwSBo4GyOWMXTvh7Gtcb36S2e1vAgQjv0BGHNPJMiL9MPR7v10BFmuuQ/Y71agjFWiQ61+89RizfA=
script:
- mvn test jacoco:report
after_success:
- mvn coveralls:report
